# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    delivery_addresses: ['%env(resolve:MAILER_TO_ADDRESS)%']
    sender_address : '%env(resolve:MAILER_FROM_ADDRESS)%'
    url : '%env(resolve:MAILER_URL)%'
